# Generated by Django 5.0 on 2024-02-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_rename_nid_passengersaccount_nid_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengersaccount',
            name='Address',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='passengersaccount',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
    ]
