# Generated by Django 5.0 on 2024-02-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0003_passengersaccount_address_passengersaccount_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengersaccount',
            old_name='Address',
            new_name='address',
        ),
    ]
