# Generated by Django 5.0 on 2024-03-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0007_alter_accountmodel_user_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengersaccount',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=100),
        ),
    ]
