# Generated by Django 5.0 on 2024-03-14 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0008_alter_passengersaccount_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengersaccount',
            name='nid_no',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999), django.core.validators.RegexValidator('^[0-9]{10}$', message='Must be a 10-digit number.')]),
        ),
    ]
