# Generated by Django 5.0 on 2024-03-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0009_alter_passengersaccount_nid_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
