# Generated by Django 5.0 on 2024-03-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0010_alter_accountmodel_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='total_buyed_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
