# Generated by Django 5.0 on 2024-02-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_alter_train_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
