# Generated by Django 5.0 on 2024-02-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_alter_train_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='destination',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='train',
            name='origin',
            field=models.CharField(default='', max_length=100),
        ),
    ]
