# Generated by Django 5.0 on 2024-03-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0004_alter_train_destination_alter_train_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
