# Generated by Django 5.0 on 2024-03-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0007_ticketbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketbooking',
            name='user',
        ),
    ]
