# Generated by Django 5.0 on 2024-03-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0009_ticketbooking_user_alter_ticketbooking_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='train_pic',
            field=models.ImageField(blank=True, null=True, upload_to='passengers/media/uploads/'),
        ),
    ]
