# Generated by Django 5.0 on 2024-03-10 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0010_train_train_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='staTrainRelationship',
        ),
        migrations.AddField(
            model_name='train',
            name='staTrainRelationship',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trains.station'),
        ),
    ]
