# Generated by Django 5.0 on 2024-03-10 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0012_alter_train_statrainrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='staTrainRelationship',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trains.station'),
        ),
    ]
