# Generated by Django 5.0 on 2024-03-10 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0014_alter_train_statrainrelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='staTrainRelationship',
        ),
        migrations.AddField(
            model_name='train',
            name='station_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='origin_station', to='trains.station'),
        ),
    ]
