# Generated by Django 5.0 on 2024-03-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0016_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='ticket_price',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
