# Generated by Django 5.0 on 2024-03-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0017_train_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooking',
            name='From',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='to',
            field=models.CharField(max_length=100),
        ),
    ]
