# Generated by Django 5.0 on 2024-03-10 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0019_alter_review_user_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trains.train'),
        ),
    ]
