# Generated by Django 5.0 on 2024-03-14 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0021_alter_review_user_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='station_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_station', to='trains.station'),
        ),
        migrations.AlterField(
            model_name='train',
            name='ticket_price',
            field=models.PositiveIntegerField(),
        ),
    ]
