# Generated by Django 5.0 on 2024-03-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0026_alter_ticketbooking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='ac_b',
        ),
        migrations.RemoveField(
            model_name='train',
            name='ac_s',
        ),
        migrations.RemoveField(
            model_name='train',
            name='f_seat',
        ),
        migrations.RemoveField(
            model_name='train',
            name='s_chair',
        ),
        migrations.RemoveField(
            model_name='train',
            name='snigdha',
        ),
    ]
